// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"sample_rmq/common/infrastructures"
	"sample_rmq/common/utilities"
	"sample_rmq/gateway/controllers"
)

// Injectors from wire.go:

func InitializeContainer() Container {
	goValidator := utilities.ProvideGoValidator()
	rmqRouter := infrastructures.ProvideRMQRouter()
	inferenceController := controllers.ProvideInferenceController(goValidator, rmqRouter)
	fiberRouter := infrastructures.ProvideFiberRouter()
	zmqBroker := infrastructures.ProvideZmqBroker()
	mainContainer := ProvideContainer(inferenceController, fiberRouter, rmqRouter, zmqBroker)
	return mainContainer
}
